apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistence-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard